name: CD

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/configure-pages@v6
      - run: bun ci
      - run: |
          bun --bun run build
          touch .vitepress/dist/.nojekyll
      - uses: actions/upload-pages-artifact@v5
        with:
          path: .vitepress/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 6
      - name: Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ github.token }}
          environment: github-pages
          onlyRemoveDeployments: true
